### ISSUE TITLE
Swarm over Metrics

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1340]
I never know which metric to choose, what the best `window` should be, etc - it asks for swarming over it. 
I'm not sure if it makes sense to change the value during the (other) swarming process, as it's used to drive swarming's direction. 
But probably it could be tried with `fixEarly` - best metric chosen and then swarm over other parameters.

**Comment by scottpurdy** [comment]
The metric is what the swarm attempts to optimize. Since a metric is necessary to decide which parameters are best, it isn't possible to swarm over the metric (if you somehow set it up it would just pick whichever metric returned the smallest number).

Ultimately the metric you use should match your application use case. So if the value of the results is linear with the absolute error then AAE would be best. The window is a little more difficult to pick but as long as you have 1500-2000+ records then 1000 is probably fine.

**Comment by breznak** [comment]
> it isn't possible to swarm over the metric (if you somehow set it up it would just pick whichever metric returned the smallest number).

Well, it is possible, but true that it's tricky. It would be a meta-heuristic that selects the heuristic used for param. optimization. I actually think the process would be quite straightforward - `select a heuristic that gives the biggest number (error)` as this has the most sensitive "info gain" on that problem. 
What would be nice is that it would completely hide the metric selection problem and there would be only one universal metric.

**Comment by scottpurdy** [comment]
That obviously wouldn't work. Take a bad metric and multiple it by a large number and it will always win.

**Comment by breznak** [comment]
True that, shutting the idea.. Thanks.
