### ISSUE TITLE
Binary pip install error [Debian / Anaconda Python]: Cap'n Proto local compilation errors

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1774]
Moved from #1773. 

gcc (Debian 4.7.2-5) 4.7.2

When running:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.1.0-cp27-none-linux_x86_64.whl

First error is:

```
    *WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
    fetching https://capnproto.org/capnproto-c++-0.5.0.tar.gz into /tmp/pip_build_esc/pycapnp/bundled
    In file included from ./src/kj/exception.h:29:0,
                     from ./src/kj/debug.h:115,
                     from src/capnp/compiler/md5.c++:43:
    ./src/kj/memory.h:213:28: error: expected ';' at end of member declaration
    ./src/kj/memory.h:213:32: error: expected unqualified-id before '{' token
    ./src/kj/memory.h:213:48: error: expected ';' at end of member declaration
    ./src/kj/memory.h:214:36: error: expected ';' at end of member declaration
    ./src/kj/memory.h:214:44: error: expected unqualified-id before '{' token
    ./src/kj/memory.h:214:60: error: expected ';' at end of member declaration
    ./src/kj/memory.h:215:29: error: expected ';' at end of member declaration
    ./src/kj/memory.h:215:19: error: 'kj::Own<T>&& kj::_::OwnOwn<T>::operator*()' cannot be overloaded
    ./src/kj/memory.h:213:18: error: with 'kj::Own<T>& kj::_::OwnOwn<T>::operator*()'
    ./src/kj/memory.h:215:34: error: expected unqualified-id before '{' token
    ./src/kj/memory.h:215:58: error: expected ';' at end of member declaration
    ./src/kj/memory.h:216:37: error: expected ';' at end of member declaration
    ./src/kj/memory.h:216:25: error: 'const kj::Own<T>&& kj::_::OwnOwn<T>::operator*() const' cannot be overloaded
    ./src/kj/memory.h:214:24: error: with 'const kj::Own<T>& kj::_::OwnOwn<T>::operator*() const'
    ./src/kj/memory.h:216:46: error: expected unqualified-id before '{' token
    ./src/kj/memory.h:216:70: error: expected ';' at end of member declaration
    make: *** [src/capnp/compiler/md5.lo] Error 1
```

There are more in the [Complete console output](http://pastebin.com/EkSX2E9V).

**Comment by esc** [comment]
I'll subscribe to this one and report back if I figure out new things.

**Comment by rhyolight** [comment]
@scottpurdy I guess we need to start thinking of a way to precompile and bundle Cap'n Proto C binaries into our binary releases. What do you think?

**Comment by rhyolight** [comment]
@esc You could try installing Cap'n Proto yourself. If there's already an installation on your computer, it should not try to re-install. The instructions are on https://capnproto.org/.

**Comment by scottpurdy** [comment]
We actually do bundle Cap'n Proto binaries with nupic.core but the pycapnp library doesn't pick them up and instead downloads and installs a separate version. This should be less error-prone since we use custom flags and specify that everything is statically linked, etc and none of that is needed for the pycapnp version. Plus it is simpler to just include pycapnp in the requirements.txt rather than having to do a separate installation with args specifying where the capnproto binaries are.

So when we see errors during pycapnp installation, I suggest that we ask people to file issues on the pycapnp project: https://github.com/jparyani/pycapnp

**Comment by scottpurdy** [comment]
Wait, I think I misinterpreted this. The pycapnp version shoudl still be compiled and included in the binary releases which is what I think @rhyolight was initially saying. So yes, I agree. I thought we already were including the Python dependencies in the wheels but I guess not? Does the pycapnp project have to build wheels separately?

**Comment by rhyolight** [comment]
The wheel describes dependencies, but does not bundle them. Perhaps there is a way to do it, but every time I install through a whl file it installs dependencies through pip and pypi. And pycapnp doesn't have anything but source code on pypi: https://pypi.python.org/pypi/pycapnp.

**Comment by llchan** [comment]
I saw this issue when I was filing capnproto issue and figured I'd chime in.  Maybe you guys have already figured this out, but capnproto now requires gcc 4.8 or better despite the README/build scripts saying 4.7 (their online docs are correct though).  My ticket (sandstorm-io/capnproto#175) was to update the README and the configure script so it dies at configure time with a more obvious message rather than a compile error.

You'll probably need to install a newer gcc either system-wide or set a bunch of env vars so it gets picked up when it goes to build the c++ lib.

**Comment by rhyolight** [comment]
@scottpurdy If @llchan is right and capnp requires gcc 4.8+, a quick fix would be to require 4.8+ gcc compiler. Another is to produce pycapnp wheels ourselves for the same target platforms as NuPIC. What are your thoughts?

**Comment by esc** [comment]
As a side note, I think you should consider making conda binaries too and distributing them through binstar:

http://conda.pydata.org/
https://binstar.org/

But that should probably be a new issue.

BTW: I have been reading Jeff's book and it's great! :)

**Comment by scottpurdy** [comment]
@rhyolight Both of those things sound like good ideas, although it would be nice if pycanp wheels mitigated the need for the newer compiler

**Comment by rhyolight** [comment]
Closing now that we are requiring gcc 4.8.
