### ISSUE TITLE
gcc: internal compiler error: Killed (program cc1plus) [Ubuntu12.04]

### ISSUE THREAD

**Issue by yajingfu** [numenta/nupic#1803]
I install Nupic accroding to the instructions of https://github.com/numenta/nupic/wiki/Installing-NuPIC-on-Ubuntu. All steps are successful except the last step of Build Nupic. I show the errors below, and I'm sorry for its length. How to solve the problem?

[Matt replaced the inline copy/paste with this link to pastebin](http://pastebin.com/aWRfB2wb).

Relevant error:

```
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4
```

**Comment by rhyolight** [comment]
A few questions:

1. what version of NuPIC are you using? (`git rev-parse HEAD` to get the SHA)
1. what version of gcc or clang are you using?
1. what version of cmake are you using?

**Comment by yajingfu** [comment]
@rhyolight 
1. abc@abc-VirtualBox:~/nupic$ git rev-parse HEAD 
5001d0eff49ecea3ccd701d617b050cbb6aff88f
2.gcc version 4.8.1 
 clang didn't install
3.cmake version 2.8.7

**Comment by rhyolight** [comment]
I think this relates to #1794.

**Comment by yajingfu** [comment]
I saw the relates questions including #1449 , but I still don't know what shoud I do specificly. I am not good at linux environment. Can you explain in detail?

**Comment by rhyolight** [comment]
I don't know exactly what the problem is yet. I'm going to try to replicate it in a VM today.

**Comment by rhyolight** [comment]
@yajingfu Ubuntu 12 comes with gcc 4.6. Did you already have gcc 4.8 installed on your system before attempting to install NuPIC? If not, I assume you installed gcc 4.8 with the instructions on https://github.com/numenta/nupic/wiki/Installing-NuPIC-on-Ubuntu, namely:

```
sudo apt-get install gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
sudo update-alternatives --config gcc
```

(The wiki page is using gcc 4.7, not 4.8, so the commands above are updated.)

If this was not the way you installed gcc 4.8, can you remember how you installed it?

**Comment by rhyolight** [comment]
@yajingfu Never mind on my last comment. I just replicated the exact same error you had on Ubuntu following the wiki instructions exactly.

**Comment by rhyolight** [comment]
I tried installing gcc 4.9 and got the same error:

```
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4
```

**Comment by rhyolight** [comment]
@yajingfu I think I figured this out. After [reading this post about the same error message](https://bitcointalk.org/index.php?topic=304389.0), I shut down my Ubuntu VM and changed the settings to give it more Base Memory. I went from 1024MB to 2048MB of Base Memory, tried rebuilding NuPIC and this time it worked!

Can you try this and tell me what happens?

**Comment by breznak** [comment]
@rhyolight cool detective work! :+1: :suspect: 
added mention to the wiki https://github.com/numenta/nupic/wiki/Installing-NuPIC-on-Ubuntu

**Comment by rhyolight** [comment]
Thanks, Marek!

**Comment by yajingfu** [comment]
@rhyolight haha, thank you, I build nupic successfully :)

**Comment by dmitry-sukhoruchkin** [comment]
Math library source file generated with SWIG math_wrap.cxx is 5490 KiB size -- maybe need to split it.

I can't compile it not with g++-4.9 not with clang-3.5 on controller Intel Edison with embedded ubilinux and with only 1 GB of memory and without swap.

Another big SWIG generated source file algorithms_wrap.cxx 3060 KiB size -- compiled ok.

root@ubilinux:~/edison/nupic# uname -a
Linux ubilinux 3.10.17-yocto-standard-r2 #7 SMP PREEMPT Thu Feb 26 09:57:06 UTC 2015 i686 GNU/Linux

root@ubilinux:~/edison/nupic# /usr/bin/clang-3.5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_32 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/edison/nupic/external/linux32/include -I/home/edison/nupic/external/common/include -I/home/edison/nupic/extensions -I/home/edison/nupic -I/home/edison/nupic/extensions/core/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c nupic/bindings/math_wrap.cxx -o build/temp.linux-i686-2.7/nupic/bindings/math_wrap.o -std=c++11 -m32 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2

clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: i386-pc-linux-gnu
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://bugs.debian.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/math_wrap-5b42de.cpp
clang: note: diagnostic msg: /tmp/math_wrap-5b42de.sh
clang: note: diagnostic msg:

Diagnostic file /tmp/math_wrap-5b42de.cpp size 25957 KiB

**Comment by kyle-sorensen** [comment]
@rhyolight Just a quick question on this issue, is there anything else you can think off the top of your head that might allow us to compile this without increasing memory?

**Comment by rhyolight** [comment]
Decrease the number of cells in each column?
