### ISSUE TITLE
Remove delta encoder special casing

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#1829]
The CLAModel has special casing for delta encoders that enable the delta encoder to be the predicted field, where the delta is fed to the model but the classifier predicts the actual, non-delta, future value. I'm not sure this is a real use-case so wanted to open an issue for discussion. The delta encoder makes sense as an auxiliary field, similar to the various ways to encode dates, but not as a way to predict the original values.

If this isn't a real use case then we can clean up a lot of special-casing code in the encoder base class and the CLAModel.

@subutai - can you comment on this?

**Comment by subutai** [comment]
I believe one use case is if you are predicting a value x that is increasing linearly. In this case the HTM will never predict well since it is a memory based system. You can instead convert the field to delta x and have the HTM predict that. The CLAModel probably has special logic so that the user doesn't need to worry about converting this back and forth - they just specify delta encoding. In addition this might make it easier to try delta encoding as a swarm option.

**Comment by scottpurdy** [comment]
That makes sense. You could still swarm on the delta encoder though since the metric on the delta is still valid. I am fine with some special casing in CLAModel but the motivation was actually special casing in the encoder base class. I will see if I can leave the functionality as is while reducing special casing outside CLAModel.
