### ISSUE TITLE
Inconsistent ScalarEncoder constructor behavior

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#1966]
Buried in `ScalarEncoder._initEncoder()`, there is the possibility for raising a `ValueError` exception suggesting that one of `n`, `radius`, or `resolution` is required, but it seems `n` is always required.  For example, if you pass `n=0`, and specify either `radius` or `resolution` to something non-zero, it raises an exception: `AttributeError: 'ScalarEncoder' object has no attribute 'rangeInternal'`

This passes, resulting in a successfully created `ScalarEncoder` instance:

```python
encoder = ScalarEncoder(3, None, None, name='scalar', n=14, radius=0, resolution=0, forced=True)
```

These fail, raising unexpected `AttributeError` exceptions:

```python
encoder1 = ScalarEncoder(3, None, None, name='scalar', n=0, radius=None, resolution=0.5, forced=True)
encoder2 = ScalarEncoder(3, None, None, name='scalar', n=0, radius=1.5, resolution=0, forced=True)
```

**Comment by oxtopus** [comment]
See https://github.com/numenta/nupic/pull/1967 for currently-failing test case to demonstrate the status quo.

**Comment by rmsmith007** [comment]
Test 1 creates the instance but fails on encoding because maxval and minval are set to None. Although the module tests these for None (eg for setting range and resolution from n) it seems these should always be set as numbers.

Test 2 fails to create the instance, but this is because radius is set to None rather than the DEFAULT_RADIUS of 0. Setting maxval and minval and defaulting radius to 0 allows both creation and encoding to work.

Test 3 uses the correct DEFAULT_RESOLUTION so once maxval and minval are set both creation and encoding works.

**Comment by cogmission** [comment]
Watch this.

**Comment by oxtopus** [comment]
@rmsmith007 correct.  The bug is that the _validation_ doesn't happen correctly, and fails due to an unexpected `AttributeError`.

**Comment by rhyolight** [comment]
@rmsmith007 If you plan on working on this, please sign our contributor license: http://numenta.org/licenses/cl/

**Comment by rmsmith007** [comment]
@rhyolight Yes, I can do that when I start tomorrow. Then there'll be a short delay while I relearn how to use git collaboratively (I'm normally a local-only branch-less type of user, which is where the changes currently are). Then I suppose I should write some tests because the current changes were based on minimising the diffs and I seem to remember something like red/green/refactor is how people should work these days.

@oxtopus OK, thanks. I had focussed on the  "three ways of setting n" initially rather than the validity of all the parameters.

**Comment by rhyolight** [comment]
> Then there'll be a short delay while I relearn how to use git collaboratively (I'm normally a local-only branch-less type of user, which is where the changes currently are).

A little dated, but this should help: https://www.youtube.com/watch?v=Yc3PKaT1knU

**Comment by rmsmith007** [comment]
@rhyolight Thanks, the video was helpful, and I now have the first pass of a fix and tests sitting in my very own github branch. I have found out that maxval and minval were allowed to be None so that AdaptiveScalarEncoder would work, which seems a bad idea. I'll have a look at how the latter might be altered to fix matters. Offhand I'd say that encapsulation would be more appropriate than inheritance and we just make a new ScalarEncoder when the AdaptiveScalarEncoder's limits change.

**Comment by rhyolight** [comment]
> I have found out that maxval and minval were allowed to be None so that AdaptiveScalarEncoder would work, which seems a bad idea. I'll have a look at how the latter might be altered to fix matters. Offhand I'd say that encapsulation would be more appropriate than inheritance and we just make a new ScalarEncoder when the AdaptiveScalarEncoder's limits change.

@scottpurdy You might have comments about the above.

**Comment by rmsmith007** [comment]
@rhyolight OK, I'm ready for a decision on which way to go. AdaptiveScalarEncoder seems to have its grubby fingers inside ScalarEncoder leading to several guarded regions for maxval/minval being None, whereas nothing in ScalarEncoder itself suggests any other behaviour than checking that they are numbers is required. By guarding another two regions (calculations dependant on rangeInternal in _initEncoder and n in __init__) with two new lines and half a dozen indents would seem to solve the immediate problem. The alternative, a better separation of the two classes, is a significantly larger effort. I also note that htm.java follows the current structure very closely. OK, so I've made the decision myself. Tomorrow I shall put in some tests, submit the quick fix to the problem as stated, and then move to something else.

**Comment by oxtopus** [comment]
Thanks, @rmsmith007.  The quick fix should suffice.  True, there are lots of opportunities for improvement in this and other encoders, but I would save that for a different issue and milestone.
