### ISSUE TITLE
PassThrough Encoders should support topology

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2062]
as `spatial pooler` now has support for topology (in inhibition), so should be the encoders, atleast some of them. 
It definitely makes sense for (sparse) `pass-through` encoder;
Use-case is for example in vision

**Comment by cogmission** [comment]
Hi Breznak,

I wonder what it means for an encoder to have topology? Intuitively I would
think that there really is no meaning for this since all dimensions can be
translated to a single dimension? Does this mean buckets would be expressed
as an Area or Volume? I'm doubting the usefulness or applicability of this
- though I'm probably not understanding something?

The impact of topology on inhibition makes sense to me, but what does it
matter for encoding - and how would two topologies for the same input value
have different encodings? (if my question makes any sense)?

Cheers,
David

On Mon, Apr 20, 2015 at 10:32 AM, breznak <notifications@github.com> wrote:

> as spatial pooler now has support for topology (in inhibition), so should
> be the encoders, atleast some of them.
> It definitely makes sense for (sparse) pass-through encoder;
> Use-case is for example in vision
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2062>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by breznak** [comment]
Hey David, 

I'm still thinking if it has a meaning for other encoders (*), but it makes sense for `*PassThrough` encoders - please see #2064 and think vision domain, where you use PassThrough encoder to just feed a matrix of values to a nupic ecosystem. 

Does that sound reasonable? 

*) A wilder use would be: "vectorizing" - implementing a VectorEncoder for any type of encoders, 
imagine scalar encoder that currently encodes a number (type `(1,1)` ), if you had `shape=(1,5)` you could encode a 1D vector of 5 numbers; decoding and buckets would have to be adjusted to that; but for PassThrough it's trivial

**Comment by breznak** [comment]
@chetan51 please review

**Comment by cogmission** [comment]
Hi Breznak,

I guess I'm just asking whether the dimensionality of the encoding confers
any useful information? A pass-through encoder doesn't actually encode
anything (I'm assuming if the implied functionality of the term "pass
through" holds true), therefore the SP just receives the input
dimensionality. So that part makes sense. But for other encoders, I don't
see how the encoding itself would vary according to the input
dimensionality? I'm not exactly sure what is happening by a "vectorizing"
encoder - but I think topology would make sense only if the dimensionality
conferred meaning (i.e. the overlapping of nearby bits conferred uniformity
in meaning). ?? I don't know... :-)

Another question about something you said earlier. I'm wondering if I
ported the SP's topological functionality or did the SP get that additional
functionality more recently?



On Mon, Apr 20, 2015 at 11:26 AM, breznak <notifications@github.com> wrote:

> @chetan51 <https://github.com/chetan51> please review
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2062#issuecomment-94500053>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by breznak** [comment]
@cogmission actually..I'm taking the bold statement back :smiling_imp: it does not make sense for other than pass-through encoders. 

SP topology - I'm meaning the support for 2D inputs and local-inhibition, either implemented by you or Chetan a couple of months ago. 

Btw, I'm hitting some inheritance trickery in python, the "dimensionality code" worked in Encoder.encode() but not in PassThrough.encode() ?

**Comment by cogmission** [comment]
:P

Ah, most of my work has been pure porting. I have done no original Python
coding, Chetan deserves all the credit for that :)

As far as inheritance trickery is concerned, I'm not a Python expert so I'm
not sure how overriding works in Python. The reason for the override (as
far as I remember) is to narrow the type of input into the "expected type"
of the inheriting child's encodeIntoArray() method, no?

On Mon, Apr 20, 2015 at 12:24 PM, breznak <notifications@github.com> wrote:

> @cogmission <https://github.com/cogmission> actually..I'm taking the bold
> statement back [image: :smiling_imp:] it does not make sense for other
> than pass-through encoders.
>
> SP topology - I'm meaning the support for 2D inputs and local-inhibition,
> either implemented by you or Chetan a couple of months ago.
>
> Btw, I'm hitting some inheritance trickery in python, the "dimensionality
> code" worked in Encoder.encode() but not in PassThrough.encode() ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2062#issuecomment-94515264>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by chetan51** [comment]
@breznak I don't understand why this change is necessary. The Spatial Pooler takes a 1D array as input to `compute`, and computes using topology specified by `inputDimensions`. Thus, any encoder should output a 1D array, and to use topology you just specify what `inputDimensions` you want the 1D array to be treated as by the Spatial Pooler.

**Comment by breznak** [comment]
for vision! there it makes sense to keep the data in 2D.
* SP supports both 2D input & 2D columns
* I'm not sure if TP supports 2D columns? Would it make sense to use SP to
translate image from 2D to 1D?

Anyway, for that I need an (pass-thru) encoder that allows 2D arrays.

**Comment by chetan51** [comment]
@breznak But the standard way we use topology in SP is to pass in 1D input and specify the dimensions of the input. I don't see why we can't use our existing 1D encoders and still support topology.

**Comment by breznak** [comment]
ok @chetan51 , can you explain for me please? 

if I have 2D data [1 2; 3 4], you say I should encode as [1 2 3 4] and specify SP inputDim=(2,2) and then columns (synapses, inhibition,..) would map as in 2D? Do I have to use SP columns arranged in 2D? (if not, why is the choice of 2D cols & input for SP useful then?) 
Thanks!

**Comment by chetan51** [comment]
@breznak That is correct. You would want to use SP columns arranged in 2D. But you don't have to feed the input in a 2D array as long as you specify the input dimensions as 2D.

**Comment by breznak** [comment]
Ok, so the 2D encoder could still be useful if you want to skip SP and pass directly to TP, but up to you; as long as the 2D with SP works, I don't sweat it. 

Btw, wouldn't it be easier (and more natural) to have the transformation logic in an encoder (to 2D, ..) and SP would only require to have the same dimensionality as the input?

**Comment by chetan51** [comment]
The TM operates similarly to the SP regarding topology; you just specify the column dimensions, and `compute` takes the active columns as input.

> Btw, wouldn't it be easier (and more natural) to have the transformation logic in an encoder (to 2D, ..) and SP would only require to have the same dimensionality as the input?

I don't know; I think it's nice that the input to SP is consistently a 1D array, and you only specify topology on initialization. That being said, feel free to bring it up as a discussion topic on the mailing list if you'd like.

**Comment by cogmission** [comment]
Hi guys, I've been wondering if the SP could simply get its input
dimensionality from the associated encoder when used with an encoder? It
should be able to adapt when used in a Network setting... The move should
always be toward fewer configurations, (IMO).

Cheers,
David

On Thu, Apr 23, 2015 at 3:25 PM, Chetan Surpur <notifications@github.com>
wrote:

> The TM operates similarly to the SP regarding topology; you just specify
> the column dimensions, and compute takes the active columns as input.
>
> Btw, wouldn't it be easier (and more natural) to have the transformation
> logic in an encoder (to 2D, ..) and SP would only require to have the same
> dimensionality as the input?
>
> I don't know; I think it's nice that the input to SP is consistently a 1D
> array, and you only specify topology on initialization. That being said,
> feel free to bring it up as a discussion topic on the mailing list if you'd
> like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic/issues/2062#issuecomment-95710191>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by rhyolight** [comment]
Can we close this issue?

**Comment by breznak** [comment]
For me, yes. Might want to answer David's question yet..

**Comment by rhyolight** [comment]
@cogmission If no one answers your question, please submit to mailing list. Thanks.

**Comment by BoltzmannBrain** [comment]
@rhyolight I think we can close the issue. @cogmission are you asking if we could remove the `inputDimensions` parameter when initializing an SP? That seems unnecessary. There are a number of reasons not to do this, including for debugging and clarity; setting this parameter distinct from an encoder allows us to verify the encoder input size matches the input size expected by the SP.

**Comment by cogmission** [comment]
Hi,

 I mention this because there will never [read rarely] be a time when the input width does not match the encoder output width when the spatial pooler is used with an encoder (in a Network context), so why mandate having to go through the extra step of specifying the input width is when it's obviously going to be whatever the output of the encoder is?

The trend in modern software is to intuit as much as possible and leave the extraneous configurations for corner cases where special needs are required; and I think nupic should follow suit.

**Comment by cogmission** [comment]
Said more clearly (perhaps), that configuration tells the spatial pooler what the dimensionality of the input to expect is,  so why mandate specifying what is retrievable programmatically from the encoder ( via Encoder.getWidth() )?

**Comment by rhyolight** [comment]
Again, I think this is a better conversation for nupic-hackers, where more people will read it.
