### ISSUE TITLE
Change hello_tp.py to use temporal_memory.py

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2548]
The file `examples/tp/hello_tp.py` is for newbies who want to learn about temporal memory. It currently uses `TP10X2`. This issue is to port the file over to use the newer and easier to understand TemporalMemory.  The language in the file should also be updated to use the term "Temporal Memory" as it still refers to the older terminology "temporal pooler".  

Specifically:

* Change name of file to hello_tm.py
* Change import to `from nupic.research.temporal_memory import TemporalMemory`
* TemporalMemory has a slightly different interface than TP10X2 so the code needs to be modified accordingly.
* TemporalMemory does not have helper functions to print the cell states, so those should be implemented.
* Change terminology in comments, etc. to say "temporal memory" and "TM" instead of "temporal pooler" and "TP"

**Comment by go-bears** [comment]
Hello subtai,

I"m a newbie contributor and would like to try tackling this bug. I would like more information about what you would like fixed. I can fix the "temporal pooler", but what phrase would replace it?

Also, I don't quite understand fix required to address the comment: "This issue is to port the file over to use the newer and easier to understand TemporalMemory and FastTemporalMemory". Instead, you would like the import statement in line 44 changed from "from nupic.research.TP10X2 import TP10X2 as TP" to "fromfrom nupic.research.temporal_memory import FastTemporalMemory"? Is this the gist of your bug report? Thank you for your time and guidance.

**Comment by subutai** [comment]
@go-bears That's great! I hope this will help you in your understanding of HTM sequence memory. I should be a little more specific about the changes and will make the edits in the main issue description.

**Comment by arhik** [comment]
@subutai 

I dont want to mess with temporalMemory code yet. So i modified the code to print the cell states for now with in the example code. Once i get used to contributions formalities i will work on it too.

Karthik.
