### ISSUE TITLE
Update readme install instructions for Linux & package nupic.bindings-latest

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2657]
The readme instructions for Linux (not OSX because that does `pip install nupic` only) have to be updated each time the `nupic.bindings` version is bumped. I suggest packaging 2 packages on each bindings release: 
* the versioned one (as so far)
* "latest" (I've seen it's a common to use pip version `999` to indicate the latest release), this is a convenience placeholder
* "upstream"  (`666` version :smiling_imp: ) on each PR merge to `.core`, w/o waiting for the version bump.

**Comment by breznak** [comment]
@rhyolight

**Comment by rhyolight** [comment]
> The readme instructions for Linux (not OSX because that does pip install nupic only) have to be updated each time the nupic.bindings version is bumped.

Actually, they don't. They need to be updated whenever there is a NuPIC release, because that is when the binary instructions are affected. Installing from binary only gets you the latest NuPIC version on pypi, which is tied to some nupic.bindings version, which may not necessarily be the latest one. We do not want to update the bindings version in the README because it may not be compatible with the latest NuPIC release.

This instruction in the README is actually [automatically updated by the release script we use](https://github.com/nupic-community/nupic.devtools/blob/master/bin/release_nupic#L314-L335) as a part of the release process. So it gets updated when it should be updated. 

And about your other ideas, I don't see the point in publishing a special pypi version for the latest, because pip knows that the latest version is the default, and it will prefer to install the latest if not given a version number. And for the "upstream" one... if people are installing from binary, they don't get the bleeding edge version of NuPIC, which is acceptable IMO. If they want the bleeding edge, they will need to compile themselves or wait for the next release, which should come pretty quickly.

**Comment by breznak** [comment]
fair enough.
