### ISSUE TITLE
MySQL setup and Swarming

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic#2676]
I'm trying to follow the Wiki to run swarming tests (https://github.com/numenta/nupic/wiki/Running-Swarms). This is on a clone of master that has been setup, but I missed install of MySQL so I've just installed that. Not sure if I have to run setup.py again?

MySQL didn't accept a blank root password during installation, so I added a simple one. Running ```$NUPIC/examples/swarm/test_db.py``` fails to connect, and says to look at ```$NUPIC/nupic/support/nupic-default.xml```. That file has been moved into ```$NUPIC/src/nupic/support```. 

The xml says not to edit the file but make a copy called ```nupic-site.xml``` and edit it. I'm not sure where to put this new XML file, or whether I should delete everything I don't need (just need to change root passwd) and just leave the bits I want? 
If I delete things should the XML format be valid? (start tags, configuration and the property to change, with associated ```/``` closing tags) Or does this site XML get inserted into the default one?

**Comment by rcrowder** [comment]
It looks like the nupic-default.xml must be copied to the nupic-site.xml and placed in the same location. setup.py re-run, and then the test_db.py successfully picks up this passwd and connects to MySQL :+1:

**Comment by kalletammemae** [comment]
Having similar problem when installing Nupic 0.5.8.dev0 on on Ubuntu 16.04 (removed older version of Nupic and cleaned system before that). The mysql was also clean installed giving simple password to root.
Everything was fine with unit tests. But swarm test was failing due to mysql access problems.
(Actually tested with mysql installed without root password, but it didn't help either).

 Copying $NUPIC/src/nupic/support/nupic-default.xml to $NUPIC/src/nupic/support/nupic-site.xml and inserting mysql root password there didn't work. But editing ~/.local/lib/python2.7/site-packages/nupic/support/nupic-default.xml changed a picture a bit:
"Retrieved the following NuPIC configuration using:  nupic-default.xml
    host   :     localhost
    port   :     3306
    user   :     root
    passwd :     *****
"

Passwd field is not empty any more! The right configuration file was hit. Still something is blocking database access continuously because the last statement didn't change:

"Couldn't connect to the database or you don't have the permissions required to create databases and tables. Please ensure you have MySQL installed, running, accessible using the NuPIC configuration settings, and the user specified has permission to create both databases and tables."

Mysql is: mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

I'm stuck currently :(

**Comment by rhyolight** [comment]
> Mysql is: mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper

I don't think we've tested with that version of MySQL. Can you try using MySQL 5.7.4 and see if it fixes it? At least I'll know what the problem is then. 

Also, the best place to have this discussion is [on our forum here](https://discourse.numenta.org/c/nupic). I would appreciate it if you posted your installation and runtime problems there, then we can identify if we need to create a bug report. 
Thanks!
