### ISSUE TITLE
Clean up partition ID in KNNClassifier

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2890]
Clean up partitionId in KNNClassifierRegion and KNNClassifier.

Rename to "sequenceId" or "patternId"
Document sequenceId even more clearly.
Take out finishLearning/restart learning logic.
Make sequenceId work efficiently all the time without requiring restart learning.
Add logic to easily disable sequenceId ignore logic.
Add tests for the above.

Related to #2741

**Comment by SaganBolliger** [comment]
I'm not sure renaming the partitionId to sequenceId is the best course of action. So far the use of sequenceId has been as a piece of debugging information that is purely informational and has no effect on the algorithm. partitionId, on the other hand, when provided, does affect the output of the KNN classifier by excluding subsets of the training vectors. 

I could see removing the partitionId functionality if it isn't needed, and implement sequenceId instead at the region level. Or both sequenceId and partitionId can coexist since they have entirely different functionality. But causing sequenceId to have side effects would be a departure from current usage in the rest of the codebase.

**Comment by subutai** [comment]
@SaganBolliger We are generalizing the meaning of partitionId to cover more cases. I actually think calling it "patternId" is clearer since it does not have to be tied to sequences or partitions.  

There will be no impact on current functionality, other than the renaming.
