### ISSUE TITLE
Implement Anomaly Likelihood Region

### ISSUE THREAD

**Issue by andrewmalta13** [numenta/nupic#3219]
- Creating a simple and clean AnomalyLikelihoodRegion
- Remove `src/nupic/algorithms/Anomaly.py` and `src/nupic/regions/AnomalyRegion.py`

**Comment by breznak** [comment]
I'm :-1: for the drastic cleanup in the PR, which removes the `Anomaly` class completely. 
1) what is the reason to break the functionality for people not using the regions? (eg. me :P )
2) as it seems, this provides only "likelihood" anomaly, not "raw"? 
I think an AnomalyRegion is a fine idea, moving it out of the CLAModel, but please don't force a functionality to a NetworkAPI (Anomaly.py vs AnomalyRegion)

**Comment by rhyolight** [comment]
@breznak has a point here. At the least, this issue should be broken out into two issues for discussion. One for removing `Anomaly` & `AnomalyRegion`, and the other for adding the `AnomalyLikelihoodRegion`.

**Comment by rhyolight** [comment]
@scottpurdy I'm happy to break this issue in twain, but @andrewmalta13 would need to split up the PR. Did we ever have a public discussion about removing `Anomaly` and `AnomalyRegion`? I don't think it's fair to do it like this.

**Comment by cogmission** [comment]
Shouldn't they be usable regardless of their inclusion in a Region or not?

**Comment by rhyolight** [comment]
> Shouldn't they be usable regardless of their inclusion in a Region or not?

Yes, but that's beside the point, isn't it?

**Comment by cogmission** [comment]
Is it? Sorry I came to this via gmail which only showed @breznak 's comment and not the entire context:

>  1) what is the reason to break the functionality for people not using the regions? (eg. me :P )

I assumed if he had to write this, then the proposal somehow broke atomic usage?

**Comment by rhyolight** [comment]
@cogmission Please read the context of posts before responding to them! Now we've got 4 off-topic posts on this issue that are distracting from the point I was trying to make yesterday.

**Comment by scottpurdy** [comment]
I think the idea here is:

1. The raw score calculation is specific to temporal memory in general, but not any specific version so we leave it in `nupic.algorithms.anomaly` and if you have an instance of TM, you can pass the active/predicted columns to that function to get a raw score. This is the same as before.
2. The anomaly likelihood isn't specific to TM. It lives separately in `nupic.algorithms.anomaly_likelihood` with a class to maintain the state. There are other ideas for refactoring this discussed here (#3228) and for later consideration. This is the same as before.
3. Others (@breznak) have wanted to experiment with other algorithms. The original take on this (the [anomaly class](https://github.com/numenta/nupic/blob/99d8b7470993d338090c414fe0dd98a24923feea/src/nupic/algorithms/anomaly.py#L56)) had two downsides. It required that people get their algorithms merged into NuPIC in order to use. And it tried to create a common interface for algorithms that had different parameters and required different state. We decided it would be better to have separate regions so people could experiment with their own algorithms simply by creating their own region. The only implementation that has been shown useful in NuPIC is the version proposed here (compute raw score and then likelihood). We'd love to see people experiment with other implementations and it should be easier now that they can use the pluggable Network API interface. Or if you don't like the Network API then don't use it, it isn't required since all of the NuPIC anomaly logic is in the raw score function and the likelihood class that can be used (or not) as you please.
4. We want to remove the Anomaly class and other algorithms that are speculative. We added them before because we didn't have any other way for @breznak to experiment with different versions. We could put the Anomaly class into a deprecated state. That seems like slowly ripping off a band aid though.

@breznak - Are you asking that we keep `Anomaly` and `AnomalyRegion`, deprecate them for some time before removing, or something else?

**Comment by scottpurdy** [comment]
Discussed with @andrewmalta13 offline and he is going to revert the changes in the PR that remove the `Anomaly` and `AnomalyRegion` classes. That will prevent backwards compatibility issues as well.
