### ISSUE TITLE
Unit Test failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by prasanthsivas** [numenta/nupic#3323]
Followed the instructions on the installation video and ran unit test. The log of failures are [here](https://gist.github.com/prasanthsivas/cbb2ae97743d878001850806e811e095) 

Encountered no errors while installation. My environment (Ubuntu 14.04.5 Desktop fresh install).

Thank you.

**Comment by rhyolight** [comment]
The tests are failing because the source code you checked out is more recent than the binary installation you used. What version of nupic did you install? Check out the code for that version before running tests. For example, of the version is "0.4.3", then run this in your git repo:

    git checkout 0.4.3

Then run tests in the same way.

**Comment by prasanthsivas** [comment]
$ pip freeze | grep nupic
nupic==0.5.5
nupic.bindings==0.4.5

and the source code version i checked out was the latest (0.5.6.dev0). Checked out the correct version. The test runs smoothly.

Thank you again!

**Comment by rhyolight** [comment]
Thanks for the report!
