### ISSUE TITLE
TemporalMemory: "activateCorrectlyPredictedColumn" Doc-string error.

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3378]
The docs for [activateCorrectlyPredictedColumn](https://github.com/numenta/nupic/blob/master/src/nupic/research/temporal_memory.py#L328) have a duplicate member description. Should be "matching" instead of "active".

Also, the parameter ```columnMatchingSegments``` is in the [method signature](https://github.com/numenta/nupic/blob/master/src/nupic/research/temporal_memory.py#L316)  _but there is no use of it in the method_. Is this because it _is_ used in an overridden method (say in research.ExtendedTemporalMemory) or something? If it isn't, I believe this method signature should be changed to remove this unused parameter?

If this is not intended, please let me know and I'll open another issue? ...and if it is intended, may I suggest that you wrap the active/matching lists in a container object or structure so that overriding methods can use whatever they need, rather than specify unused items which appear to contaminate the interface? Just a suggestion, because I'm not sure how to handle this in Python? 😉

**Comment by mrcslws** [comment]
Nice catch on the duplicate param in the docstring.

The second thing is intentional: https://github.com/numenta/nupic/commit/6c9a5200bf4c74962b8de20ccd9a34e719eac1ab

~~~
Give more information to the extensible methods.

Previously we were only giving the information that is needed by the
current implementation. But extensions might need more,
e.g. punishPredictedColumn might treat winner cells differently.
~~~

These methods exist for extensibility. The TM would be less extensible if, for example, an overridden `activatePredictedColumn` method couldn't use the matching segments. Basically, `activateCells` is calling these black-box methods. It gives the methods all of the possibly-relevant state because it doesn't know which subset of the state will be used (because the method is a black box).

**Comment by cogmission** [comment]
@mrcslws Ok, I suspected that might be the case - but in my capacity as a "last check buffer" (since I naturally review every line of the code during porting) - I just wanted to be sure... 😉
