### ISSUE TITLE
Add Prediction to SP & Per-Cell Feedforward Dendrites

### ISSUE THREAD

**Issue by fergalbyrne** [numenta/nupic#415]
Jeff's theory reflects the fact that predictive cells are partially depolarised by distal inputs, and so will have enhanced activations when provided with feedforward inputs. This is missing in the SP. In addition, the SP uses a common dendrite for all the cells, whereas they have their own dendrites in the theory. This can be remedied with just a few lines of code and a small memory/CPU cost. The benefits can be established by swarming on this enhancement for different types of data.
More on this (with pseudocode) here: http://inbits.com/2013/11/adding-prediction-to-the-nupic-spatial-pooler/

**Comment by chessweb01** [comment]
How about combining the classes TemporalMemory (or TP?) and SpatialPooler in a way that realizes Fergal's idea?

**Comment by cogmission** [comment]
In my opinion, ideally, there should be a separate structure that contains the column cell matrix and state. The Connections object is currently being separated out to fulfill this role. (I also think at that point (of after) the state should be separated out, and the structure should be moved into a entity entitled "Layer"). Layers have a columnar/cell matrix structure, and the state should exist in the "Connections" object. 

After that the columns could conceivably be "primed" for or have some variable representing a depolarized state - since the reason for a single dendrite is to represent the cells in a micro-column having the same feed forward response. The "overlap" scoring could include a "boost" from the existence of depolarized cells in a certain column; arising from distal dendritic/synaptic activity.

If understand @fergalbyrne 's ideas correctly?

**Comment by david-ragazzi** [comment]
> How about combining the classes TemporalMemory (or TP?) and SpatialPooler in a way that realizes @fergalbyrne 's idea? 

I was quite favor of combining spatial and temporal classes a time ago but I changed my mind. As a class evoluate or even is replaced then all combined super classes also need be updated (look the old spatial pooler [AKA `FDRCSpatial2`] case, for example). Furthermore, we would need have several combined classes to attend each implementation (for example, Comb1=SP+TM_v1, Comb2=SP+TM_v2, etc). Because this, Network class is essential. I'm favor of keep implementations in a independent way in order to avoid such additional maintenance work BUT make such implementations use the same shared abstract model of objects to store states of Columns, Cells, Segments, etc. This way we could change the spatial and temporal implementations but without change the structure of such neuronal model of objects. In my opinion, Connections class is a first step in this path.

**Comment by david-ragazzi** [comment]
@cogmission oohh.. We are thinking the same.. You was quicker than me!!

**Comment by fergalbyrne** [comment]
Thanks guys for hopping on to this, it's deeply appreciated. I'll be making some comments which might help us organise our thinking and get things rolling.

**Comment by fergalbyrne** [comment]
OK. We're going to add a repo to nupic-community for algorithm research, and do everything external to nupic itself (this is how nupic.research works, using nupic as a library and subclassing). This way we avoid the whole PR-CI cycle, and we can set up our own tests and prototype quickly. Any comments or objections? Also, not sure who is to set that up... @subutai might know..

**Comment by david-ragazzi** [comment]
@fergalbyrne Do you mean a `front-end` for nupic?

**Comment by fergalbyrne** [comment]
@cogmission and @david-ragazzi I think we should just do the simplest thing that'll work, which is to create a single PACLALayer class which has the interfaces of both SP and TM. If we need to, we can create a PASPLayer and a PATMLayer which inherit from SP and TM respectively, but just proxy to the same PACLALayer to do the work.

**Comment by fergalbyrne** [comment]
@david-ragazzi Not sure what that means. @subutai suggested this, he uses this model for both nupic.research and his own repo.

**Comment by fergalbyrne** [comment]
OK, I have to go to a meeting. I'll try and rejoin the conversation in a couple of hours. Thanks again!

**Comment by fergalbyrne** [comment]
(as he leaves) Thanks Matt for https://github.com/nupic-community/community.research !

**Comment by subutai** [comment]
@david-ragazzi This comes from another discussion. Matt will announce this on the mailing lists - we'll see if it sticks!

**Comment by cogmission** [comment]
@fergalbyrne this may not be germane at this point, but I would be happy to whip up a Java version (pretty sure I could sit down and do it in one session)? Otherwise my contribution is pretty much finito (after any design discussions I may participate in). :-/

**Comment by david-ragazzi** [comment]
> @david-ragazzi This comes from another discussion. Matt will announce this on the mailing lists - we'll see if it sticks!

oohh.. I look forward for this..

**Comment by david-ragazzi** [comment]
> @david-ragazzi This comes from another discussion. Matt will announce this on the mailing lists - we'll see if it sticks!

oohh.. I look forward for this!!

**Comment by cogmission** [comment]
@david-ragazzi Have you been following the "Re: Cortical Learning Algorithm (CLA)" thread? Fergal suggests a slight change (may be more than slight in effect, though) to the CLA algorithm. I remember him talking about this back when I didn't know what a cortical column was! :-P  But, now it seems like he's going to get to try it out. 

**NOTE:**
I think the degree of depolarization should be kept on a "column object" (or indexed into the Connections object as a column variable - in Python NuPIC terms) - rather than trying to separately store the value on an individual cell. This way we keep the uniform feed-forward aspect of the single proximal dendrite; and we lessen the processing and looping.

**Comment by rhyolight** [comment]
Ok guys, https://github.com/nupic-community/community.research has a decent README and is open for business. Contact me or another `nupic-community` owner for access.
